services:
  canasta-client:
    image: canasta-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: $VITE_SERVER_URL
    restart: unless-stopped
    ports:
      - "4000:8080"
