// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
/**
 * This file is auto-generated from Go structs.
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Generated by tygo from internal/server/api_types.go
 */

//////////
// source: api_types.go

/**
 * ============================================================================
 * ERROR RESPONSES
 * ============================================================================
 * tygo:generate
 */
export interface ErrorMessage {
  message: string
  code?: string
}
/**
 * ============================================================================
 * CREATE GAME (create_game)
 * ============================================================================
 * tygo:generate
 */
export interface CreateGameRequest {
  username: string
  randomTeamOrder: boolean
}
/**
 * tygo:generate
 */
export interface CreateGameResponse {
  roomCode: string
  token: string
  playerId: number /* int */
}
/**
 * ============================================================================
 * JOIN GAME (join_game)
 * ============================================================================
 * tygo:generate
 */
export interface JoinGameRequest {
  roomCode: string
  username: string
}
/**
 * tygo:generate
 */
export interface JoinGameResponse {
  success: boolean
  token: string
  playerId: number /* int */
  message?: string
}
/**
 * ============================================================================
 * RECONNECT (reconnect) - Phase 3
 * ============================================================================
 * tygo:generate
 */
export interface ReconnectRequest {
  token: string
}
/**
 * tygo:generate
 */
export interface ReconnectResponse {
  success: boolean
  message?: string
  roomCode?: string
  playerId?: number /* int */
}
/**
 * tygo:generate
 */
export interface PlayerStatusNotification {
  playerId: number /* int */
  username: string
  connected: boolean
}
/**
 * tygo:generate
 */
export interface GameResumedNotification {
  message: string
}
/**
 * tygo:generate
 */
export interface GamePausedNotification {
  message: string
}
/**
 * tygo:generate
 */
export interface DisconnectedElsewhereNotification {
  message: string
}
/**
 * ============================================================================
 * SET READY (set_ready)
 * ============================================================================
 * tygo:generate
 */
export interface SetReadyRequest {
  ready: boolean
}
/**
 * ============================================================================
 * UPDATE TEAM ORDER (update_team_order)
 * ============================================================================
 * tygo:generate
 */
export interface UpdateTeamOrderRequest {
  playerOrder: string[]
}
/**
 * ============================================================================
 * LEAVE GAME (leave_game)
 * ============================================================================
 * tygo:generate
 */
export interface LeaveGameRequest {}
/**
 * ============================================================================
 * LOBBY STATE (lobby_update broadcast)
 * ============================================================================
 * tygo:generate
 */
export interface LobbyState {
  roomCode: string
  players: LobbyPlayer[]
  playerCount: number /* int */
  randomTeamOrder: boolean
  status: string
  allReady: boolean
}
/**
 * tygo:generate
 */
export interface LobbyPlayer {
  username: string
  ready: boolean
  connected: boolean
  isYou: boolean // Personalized for each client
}
/**
 * ============================================================================
 * GAME STARTED (game_started broadcast)
 * ============================================================================
 * tygo:generate
 */
export interface GameStartedNotification {
  message: string
}
/**
 * ============================================================================
 * GAME STATE (game_state broadcast) - Phase 4
 * ============================================================================
 * tygo:generate
 */
export interface GameStateMessage {
  state: any // *canasta.ClientState - using interface{} to avoid circular import
  currentPlayer: number /* int */
  phase: string
  status: string
}
/**
 * ============================================================================
 * EXECUTE MOVE (execute_move) - Phase 5
 * ============================================================================
 * tygo:generate
 */
export interface MoveRequest {
  type: string // Move type from canasta package (e.g., "draw_from_deck")
  ids?: number /* int */[] // Card IDs for moves that require multiple cards
  id?: number /* int */ // Single card ID for moves that require one card
  fromFoot?: boolean // For play_red_three: true if from foot (no draw), false if from hand (draw replacement)
}
/**
 * tygo:generate
 */
export interface MoveResultResponse {
  success: boolean
  message?: string
}
/**
 * ============================================================================
 * HAND/GAME END NOTIFICATIONS - Phase 5
 * ============================================================================
 * tygo:generate
 */
export interface HandEndedNotification {
  handNumber: number /* int */ // Hand that just ended
  teamAScore: number /* int */ // Team A's total score
  teamBScore: number /* int */ // Team B's total score
  nextHandReady: boolean // true if starting new hand, false if game ended
}
/**
 * tygo:generate
 */
export interface GameEndedNotification {
  teamAScore: number /* int */
  teamBScore: number /* int */
  winnerTeam: string // "TeamA" or "TeamB"
}
/**
 * tygo:generate
 */
export interface ServerShutdownNotification {
  message: string
}
/**
 * tygo:generate
 */
export interface PermissionRequestNotification {
  requestingPlayer: number /* int */
  requestingName: string
}
/**
 * tygo:generate
 */
export interface PermissionResponseNotification {
  approved: boolean
}

//////////
// source: connections.go

export interface PlayerConnection {
  GameID: string
  PlayerID: number /* int */
  Username: string
  Token: string
}
export interface ConnectionManager {}

//////////
// source: game_manager.go

export interface GameManager {}
export interface ActiveGame {
  Game?: any /* canasta.Game */
  RoomCode: string
  Config: LobbyConfig
  Status: GameStatus
  Players: PlayerSlot[]
  CreatedAt: string
  UpdatedAt: string
  LobbyExpiry: string
}
export interface LobbyConfig {
  PlayerOrder: string[]
  RandomTeamOrder: boolean
}
export interface PlayerSlot {
  Username: string
  Token: string
  Connected: boolean
  Ready: boolean
  JoinedAt: string
}
export type GameStatus = string
export const StatusLobby: GameStatus = 'lobby'
export const StatusPlaying: GameStatus = 'playing'
export const StatusPaused: GameStatus = 'paused'
export const StatusCompleted: GameStatus = 'completed'

//////////
// source: messages.go

export interface ClientMessage {
  type: string
  payload: any /* json.RawMessage */
}
export interface ServerMessage {
  type: string
  payload: any
}

//////////
// source: middleware.go

/**
 * RateLimiter implements per-connection rate limiting using a sliding window algorithm
 * Why sliding window: Prevents burst attacks while allowing consistent legitimate traffic
 * Why per-connection: One abusive client shouldn't affect others
 */
export interface RateLimiter {}
/**
 * ConnectionHealth tracks last activity time for each connection
 * Used for detecting dead/inactive connections
 * Why separate from RateLimiter: Different concerns - health vs abuse prevention
 */
export interface ConnectionHealth {}

//////////
// source: persistence.go

/**
 * PersistenceManager handles saving and loading game state to/from database
 */
export interface PersistenceManager {}

//////////
// source: server.go

export interface Server {}

//////////
// source: session_manager.go

export interface SessionInfo {
  Token: string
  RoomCode: string
  PlayerID: number /* int */
  Username: string
}
export interface SessionManager {}
