// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
/**
 * This file is auto-generated from Go structs.
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Generated by tygo from internal/canasta/*.go
 */

//////////
// source: canasta.go

export interface Game {
  id: string
  players: (Player | undefined)[]
  teamA?: Team
  teamB?: Team
  hand?: Hand
  handNumber: number /* int */
  currentPlayer: number /* int */
  phase: TurnPhase
  goOutRequestPending: boolean // True when permission request is active
  goOutRequester: number /* int */ // Player ID who asked permission (-1 if none)
  goOutPartner: number /* int */ // Partner ID who needs to respond (-1 if none)
}
export type TurnPhase = string
export const PhaseDrawing: TurnPhase = 'drawing'
export const PhasePlaying: TurnPhase = 'playing'
export interface Hand {
  deck?: Deck
  discardPile: Card[]
}
export interface Player {
  name: string
  team?: Team
  hand: PlayerHand
  foot: Card[]
  stagingMelds: Meld[]
  madeCanasta: boolean
}
export type PlayerHand = { [key: number /* int */]: Card }
export type HasId = any
export interface Meld {
  id: number /* int */
  rank: Rank
  cards: Card[]
  wildCount: number /* int */
}
export interface Canasta {
  id: number /* int */
  rank: Rank
  cards: Card[]
  count: number /* int */
  natural: boolean
}
export interface Team {
  score: number /* int */
  melds: Meld[]
  canastas: Canasta[]
  goneDown: boolean
  canGoOut: boolean
  RedThrees: Card[]
}
export interface GameConfig {
  RandomTeamOrder: boolean
}
export type GameOption = any

//////////
// source: cards.go

export type Suit = number /* int */
export const Hearts: Suit = 0
export const Diamonds: Suit = 1
export const Clubs: Suit = 2
export const Spades: Suit = 3
export type Rank = number /* int */
export const Four = 0
export const Five = 1
export const Six = 2
export const Seven = 3
export const Eight = 4
export const Nine = 5
export const Ten = 6
export const Jack = 7
export const Queen = 8
export const King = 9
export const Ace = 10
export const Two = 11
export const Joker = 12
export const Three = 13
export const Wild = 14
export interface Card {
  id: number /* int */
  suit: Suit
  rank: Rank
}
export interface Deck {
  cards: Card[]
}

//////////
// source: handler.go

export type MoveType = string
/**
 * Draw phase
 */
export const MoveDrawFromDeck: MoveType = 'draw_from_deck'
export const MovePickupDiscardPile: MoveType = 'pickup_discard_pile'
/**
 * Play phase
 */
export const MoveCreateMeld: MoveType = 'create_meld'
export const MoveAddToMeld: MoveType = 'add_to_meld'
export const MoveBurnCards: MoveType = 'burn_card'
export const MoveGoDown: MoveType = 'go_down'
/**
 * End phase moves
 */
export const MoveDiscard: MoveType = 'discard'
/**
 * Special moves
 */
export const MoveAskToGoOut: MoveType = 'ask_to_go_out'
export const MoveRespondGoOut: MoveType = 'respond_go_out'
export const MovePickupFoot: MoveType = 'pickup_foot'
export const MovePlayRedThree: MoveType = 'play_red_three'
export interface Move {
  PlayerId: number /* int */
  Type: MoveType
  Id: number /* int */
  Ids: number /* int */[]
  FromFoot: boolean // True if red threes came from foot (no replacement draw)
}
export interface MoveResponse {
  success: boolean
  message: string
}

//////////
// source: presentation.go

export interface ClientState {
  deckCount: number /* int */
  discardCount: number /* int */
  discardTopCard?: Card // Pointer so we can send nil when pile is empty
  name: string
  hand: PlayerHand
  hasFoot: boolean
  players: OtherPlayerState[]
  ourScore: number /* int */
  ourMelds: Meld[]
  ourCanastas: Canasta[]
  ourRedThrees: Card[]
  otherScore: number /* int */
  otherMelds: Meld[]
  otherCanastas: Canasta[]
  otherRedThrees: Card[]
  goOutRequestPending: boolean // Is there an active permission request?
  isGoOutRequester: boolean // Is this player the one who asked?
  isGoOutPartner: boolean // Is this player the one who needs to respond?
}
export interface OtherPlayerState {
  name: string
  handLength: number /* int */
  hasFoot: boolean
}
