// Code generated by tygo. DO NOT EDIT.
import type { ClientState, TurnPhase } from "./canasta";

//////////
// source: errors.go

/**
 * ErrorCode identifies why a command was rejected.
 */
export type ErrorCode = string;
/**
 * Server-native codes, produced outside internal/canasta. Note:
 * there's no code here for a bad room code, a missing/blank name, or a
 * full room — those are all rejected as plain HTTP errors before a
 * websocket connection (and thus any ErrorPayload) can exist at all;
 * see internal/server/ws_handler.go.
 */
export const ErrNotYourTurn: ErrorCode = "NOT_YOUR_TURN";
export const ErrWrongPhase: ErrorCode = "WRONG_PHASE";
export const ErrNotPartner: ErrorCode = "NOT_PARTNER";
export const ErrRoomNotPlaying: ErrorCode = "ROOM_NOT_PLAYING";
export const ErrUnknownType: ErrorCode = "UNKNOWN_MESSAGE_TYPE";
export const ErrInvalidPayload: ErrorCode = "INVALID_PAYLOAD";
/**
 * Fallback for any internal/canasta error that doesn't follow the
 * "CODE: message" convention.
 */
export const ErrValidation: ErrorCode = "VALIDATION_ERROR";

//////////
// source: messages.go
/*
Package protocol defines the websocket wire format shared by the room
actor and the transport layer: message envelopes, per-command payloads,
state snapshots, and error codes. It has no I/O of its own.
*/

/**
 * MessageType identifies what kind of envelope a ClientMessage/ServerMessage
 * carries. A named type (rather than a bare string) lets these values be
 * generated as a real TypeScript enum by tygo.
 */
export type MessageType = string;
/**
 * ClientMessage is the envelope for every message a client sends.
 */
export interface ClientMessage {
  type: MessageType;
  data: unknown;
}
/**
 * ServerMessage is the envelope for every message sent to a client.
 */
export interface ServerMessage {
  type: MessageType;
  data: unknown;
}
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeDrawFromDeck: MessageType = "draw_from_deck";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypePickUpDiscardPile: MessageType = "pick_up_discard_pile";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeNewMeld: MessageType = "new_meld";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeAddToMeld: MessageType = "add_to_meld";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeBurnCards: MessageType = "burn_cards";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeGoDown: MessageType = "go_down";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeDiscard: MessageType = "discard";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypePickUpFoot: MessageType = "pick_up_foot";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypePlayRedThree: MessageType = "play_red_three";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeGrantPermissionToGoOut: MessageType = "grant_permission_to_go_out";
/**
 * Client -> server message types. One per internal/canasta mutator, plus
 * the permission-to-go-out handshake. Identity (name) is established at
 * connection time (see internal/room.Room.Join), not via an in-band
 * message.
 */
export const TypeAskToGoOut: MessageType = "ask_to_go_out";
/**
 * Server -> client message types.
 */
export const TypeWelcome: MessageType = "welcome";
/**
 * Server -> client message types.
 */
export const TypeState: MessageType = "state";
/**
 * Server -> client message types.
 */
export const TypePlayersLobby: MessageType = "players_lobby";
/**
 * Server -> client message types.
 */
export const TypePlayerDisconnected: MessageType = "player_disconnected";
/**
 * Server -> client message types.
 */
export const TypePlayerReconnected: MessageType = "player_reconnected";
/**
 * Server -> client message types.
 */
export const TypePlayerStatus: MessageType = "player_status";
/**
 * Server -> client message types.
 */
export const TypeGoOutRequested: MessageType = "go_out_requested";
/**
 * Server -> client message types.
 */
export const TypeError: MessageType = "error";
/**
 * CreateRoomResponse is the body of a successful POST /rooms. It's the
 * only HTTP (non-websocket) wire type, but lives here rather than in
 * internal/server so all wire types stay in one place for tygo.
 */
export interface CreateRoomResponse {
  roomCode: string;
}
/**
 * PickUpDiscardPilePayload claims the discard pile by forming a new meld
 * from the player's own cards plus the top discard card.
 */
export interface PickUpDiscardPilePayload {
  cardIds: number /* int */[];
}
/**
 * NewMeldPayload starts a new meld (or staging meld) from hand cards.
 */
export interface NewMeldPayload {
  cardIds: number /* int */[];
}
/**
 * AddToMeldPayload adds hand cards to an existing team meld.
 */
export interface AddToMeldPayload {
  cardIds: number /* int */[];
  meldId: number /* int */;
}
/**
 * BurnCardsPayload adds hand cards to an existing completed canasta.
 */
export interface BurnCardsPayload {
  cardIds: number /* int */[];
  canastaId: number /* int */;
}
/**
 * DiscardPayload discards a single card, ending the player's turn.
 */
export interface DiscardPayload {
  cardId: number /* int */;
}
/**
 * PlayRedThreePayload plays one or more red threes from hand or foot.
 */
export interface PlayRedThreePayload {
  cardIds: number /* int */[];
  fromFoot: boolean;
}
/**
 * GoOutRequestedPayload notifies exactly one seat — the asker's
 * partner — that their partner wants to go out. See applyAskToGoOut in
 * internal/room/dispatch.go.
 */
export interface GoOutRequestedPayload {
  askerName: string;
}
/**
 * WelcomePayload is sent immediately after a successful join/reconnect.
 */
export interface WelcomePayload {
  seatIndex: number /* int */;
  roomCode: string;
  roomState: string;
}
/**
 * LobbySeat describes one seat while a room is still in its Lobby state.
 */
export interface LobbySeat {
  seatIndex: number /* int */;
  name: string;
  connected: boolean;
}
/**
 * PlayersLobbyPayload is broadcast to all connected seats while a room
 * waits for its remaining players to join.
 */
export interface PlayersLobbyPayload {
  seats: LobbySeat[];
}
/**
 * PlayerStatusPayload notifies clients of a seat's connection status, e.g.
 * "disconnected", "reconnected", or "away" after the grace period elapses.
 */
export interface PlayerStatusPayload {
  seatIndex: number /* int */;
  status: string;
}
/**
 * ErrorPayload is sent to a single requester when their command is
 * rejected; no broadcast happens since no mutation occurred.
 */
export interface ErrorPayload {
  code: string;
  message: string;
}

//////////
// source: state.go

/**
 * StateMessage layers session/turn information on top of the existing
 * per-player redacted view from internal/canasta, which has no notion of
 * seats, turns, or connections. Embedding (rather than extending
 * canasta.ClientState itself) keeps internal/canasta free of transport
 * concerns while ClientState stays reusable on its own.
 */
export interface StateMessage extends ClientState {
  seatIndex: number /* int */;
  currentPlayer: number /* int */;
  isYourTurn: boolean;
  phase: TurnPhase;
  handNumber: number /* int */;
  gameOver: boolean;
  winner?: string;
  canGoOut: boolean;
}
